name: "camera"
manufacturer: ""
series: ""
description: ""
driver:
  version: "ros1"
  type: "ros"
  name: "ros_rgb_camera_driver"
rgb:
  support: true
  encoding: "bgr8"
  target: "/camera/color/image_raw" # Topic in ros or function in class
  width: 320
  height: 240
  actual_hz: 30
  origin_hz: 30
  pan: # pan value allowed for the camera platform
    min: -2.7
    max: 2.6
  tilt:
    min: -1.4
    max: 1.75
info:
  target: "/camera/color/camera_info"
  actual_hz: 30
  origin_hz: 30
pcd:
  support: false
requirement:  # Used to generate ros package.
  - cv_bridge
  - std_msgs
  - sensor_msgs
